language: python
python:
  - "3.5"
# command to install dependencies
before_install: 
    - git submodule init
    - git submodule update
install:
    - pip install -r requirements.txt
    - pip install -r RULEngine/requirements.txt
# command to run tests
script: nosetests
notifications:
    slack: 
        on_success: change
        on_failure: always
        rooms:
            - robocupulaval:TyyFRQ6Tpv49h1bmIlXJNfxu#team-ia-github
    email:
        recipients:
            - alexandre.gingras-courchesne.1@ulaval.ca
            - julien_morissette@outlook.com
            - maxime.menard.1@ulaval.ca
        on_success: change
        on_failure: always
